In [1]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [2]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')

В датасете Admission_Predict_Ver1.1.csv находятся данные об абитуриентах и вероятности приёма их в магистратуру.

Целевой переменной является вероятность приёма в университет — Chance of Admit (ranging from 0 to 1 )

Признаки: 

1. GRE Scores ( out of 340 ) — баллы по GRE тестированию
2. TOEFL Scores ( out of 120 ) — баллы по экзамену TOEFL
3. University Rating ( out of 5 ) — рейтинг университета 
4. Statement of Purpose Strength ( out of 5 ) — весомость мотивационного письма
5. Letter of Recommendation Strength ( out of 5 ) — весомость рекомендационных писем
6. Undergraduate GPA ( out of 10 ) — средний балл в бакалавриате
7. Research Experience ( either 0 or 1 ) — наличие опыта исследовательской работы ( нет / есть)

In [5]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         500 non-null    int64  
 1   GRE Score          500 non-null    int64  
 2   TOEFL Score        500 non-null    int64  
 3   University Rating  500 non-null    int64  
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64  
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB


Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [12]:
df_corr = df[['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA', 'Research', 'Chance of Admit ']]
df_corr.corr()

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.827200           0.635376  0.613498   
TOEFL Score         0.827200     1.000000           0.649799  0.644410   
University Rating   0.635376     0.649799           1.000000  0.728024   
SOP                 0.613498     0.644410           0.728024  1.000000   
LOR                 0.524679     0.541563           0.608651  0.663707   
CGPA                0.825878     0.810574           0.705254  0.712154   
Research            0.563398     0.467012           0.427047  0.408116   
Chance of Admit     0.810351     0.792228           0.690132  0.684137   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.541563  0.810574  0.467012          0.792228  
University Rating  0.608651  0.705254  0.427047          0.690132  
SOP                0.663707  0.712154  0.408116          0.684137  
LOR                1.000000  0.637469  0.372526          0.645365  
CGPA               0.637469  1.000000  0.501311          0.882413  
Research           0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.645365  0.882413  0.545871          1.000000

In [20]:
df_corr_0 = df_corr.loc[df_corr.Research == 0]
df_corr_0.corr(method='pearson')

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.680668           0.384715  0.371424   
TOEFL Score         0.680668     1.000000           0.495748  0.476563   
University Rating   0.384715     0.495748           1.000000  0.607496   
SOP                 0.371424     0.476563           0.607496  1.000000   
LOR                 0.365864     0.470956           0.484262  0.618680   
CGPA                0.678476     0.696774           0.516427  0.547098   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.603827     0.622458           0.428580  0.470188   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.365864  0.678476       NaN          0.603827  
TOEFL Score        0.470956  0.696774       NaN          0.622458  
University Rating  0.484262  0.516427       NaN          0.428580  
SOP                0.618680  0.547098       NaN          0.470188  
LOR                1.000000  0.562517       NaN          0.542528  
CGPA               0.562517  1.000000       NaN          0.752714  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.542528  0.752714       NaN          1.000000

In [21]:
df_corr_1 = df_corr.loc[df_corr.Research == 1]
df_corr_1.corr(method='pearson')

GRE Score  TOEFL Score  University Rating       SOP  \
GRE Score           1.000000     0.824170           0.614739  0.613318   
TOEFL Score         0.824170     1.000000           0.602445  0.629436   
University Rating   0.614739     0.602445           1.000000  0.723126   
SOP                 0.613318     0.629436           0.723126  1.000000   
LOR                 0.443374     0.436199           0.573881  0.591858   
CGPA                0.806720     0.784173           0.692237  0.717750   
Research                 NaN          NaN                NaN       NaN   
Chance of Admit     0.802439     0.787180           0.713094  0.708238   

                       LOR       CGPA  Research  Chance of Admit   
GRE Score          0.443374  0.806720       NaN          0.802439  
TOEFL Score        0.436199  0.784173       NaN          0.787180  
University Rating  0.573881  0.692237       NaN          0.713094  
SOP                0.591858  0.717750       NaN          0.708238  
LOR                1.000000  0.564794       NaN          0.588558  
CGPA               0.564794  1.000000       NaN          0.892489  
Research                NaN       NaN       NaN               NaN  
Chance of Admit    0.588558  0.892489       NaN          1.000000

In [23]:
df_corr_OLS = df_corr_0[['TOEFL Score', 'CGPA']]
np.shape(df_corr_OLS)

(220, 2)

In [24]:
# Создаем вектор из единиц для коэффициента w_0 и записываем все векторы в СТОЛБЦЫ матрицы признаков А
TOEFL_Score=df_corr_OLS['TOEFL Score']
CGPA= df_corr_OLS['CGPA']
A= np.column_stack((np.ones(220), TOEFL_Score, CGPA))
A

array([[  1.  , 103.  ,   8.21],
       [  1.  , 101.  ,   7.9 ],
       [  1.  , 102.  ,   8.  ],
       [  1.  , 108.  ,   8.6 ],
       [  1.  , 105.  ,   8.3 ],
       [  1.  , 107.  ,   8.7 ],
       [  1.  , 110.  ,   8.8 ],
       [  1.  , 102.  ,   8.5 ],
       [  1.  , 114.  ,   8.4 ],
       [  1.  , 109.  ,   8.8 ],
       [  1.  ,  93.  ,   7.2 ],
       [  1.  ,  99.  ,   7.3 ],
       [  1.  , 106.  ,   8.4 ],
       [  1.  , 105.  ,   7.8 ],
       [  1.  , 105.  ,   7.5 ],
       [  1.  , 108.  ,   7.7 ],
       [  1.  , 117.  ,   9.1 ],
       [  1.  , 119.  ,   9.7 ],
       [  1.  , 110.  ,   8.  ],
       [  1.  , 103.  ,   7.7 ],
       [  1.  , 102.  ,   7.4 ],
       [  1.  ,  99.  ,   7.6 ],
       [  1.  , 104.  ,   8.3 ],
       [  1.  , 100.  ,   8.1 ],
       [  1.  , 101.  ,   8.2 ],
       [  1.  , 111.  ,   8.7 ],
       [  1.  , 112.  ,   8.92],
       [  1.  , 114.  ,   9.02],
       [  1.  , 106.  ,   8.9 ],
       [  1.  ,  99.  ,   8.22],
       [  

In [29]:
# Создаем целевой вектор
y = df_corr_0[['Chance of Admit ']] # объект типа dataframe - то, что нужно

In [30]:
# вычислим OLS оценку для коэффициентов
w_hat=np.linalg.inv(A.T@A)@A.T@y
w_hat

Chance of Admit 
0         -1.044864
1          0.004427
2          0.148077

In [32]:
# прогноз
# добавились данные по новому городку:
TOEFL_Score_new = 107
CGPA_new=9.1
# делаем прогноз типичной соимости дома
Chance_new=round(w_hat.iloc[0], 3)+round(w_hat.iloc[1], 3)*TOEFL_Score_new+round(w_hat.iloc[2], 3)*CGPA_new
Chance_new

Chance of Admit     0.7298
dtype: float64

Стандартизация данных

In [33]:
# метод .mean() позволяет вычислить арифметическое среднее значение вектора
meanTOEFL_Score = df_corr_OLS['TOEFL Score'].mean()
meanCGPA  = df_corr_OLS['CGPA'].mean()
mean_y = y.mean()
print('mean value of TOEFL_Score:', meanTOEFL_Score)
print('mean value of CGPA:', meanCGPA)
print('mean value of Chance of Admit:', mean_y)

mean value of TOEFL_Score: 103.99090909090908
mean value of CGPA: 8.234727272727275
mean value of Chance of Admit: Chance of Admit     0.634909
dtype: float64


In [34]:
# Центрирование
TOEFL_Score_c = df_corr_OLS['TOEFL Score'] - meanTOEFL_Score
CGPA_c = df_corr_OLS['CGPA'] - meanCGPA
y_c = y - mean_y

In [35]:
# вычисляем длины векторов для нормирования
TOEFL_Score_c_norm = np.linalg.norm(TOEFL_Score_c)
CGPA_c_norm = np.linalg.norm(CGPA_c)
y_c_norm = np.linalg.norm(y_c)
print('norm of TOEFL_Score:\n', TOEFL_Score_c_norm)

norm of TOEFL_Score:
 71.24592492333733


In [36]:
# Нормирование: делим каждый центрированный вектор на его длину
TOEFL_Score_st=TOEFL_Score_c / TOEFL_Score_c_norm
CGPA_st=CGPA_c / CGPA_c_norm
y_st=y_c / y_c_norm

In [37]:
# Матрица центрированных признаков - БЕЗ константы!
A_st=np.column_stack(( TOEFL_Score_st, CGPA_st))
A_st

array([[-0.01390829, -0.00356568],
       [-0.04198007, -0.04826775],
       [-0.02794418, -0.03384772],
       [ 0.05627116,  0.05267241],
       [ 0.01416349,  0.00941234],
       [ 0.04223527,  0.06709243],
       [ 0.08434294,  0.08151245],
       [-0.02794418,  0.03825238],
       [ 0.1404865 ,  0.02383236],
       [ 0.07030705,  0.08151245],
       [-0.1542672 , -0.1492079 ],
       [-0.07005185, -0.13478788],
       [ 0.02819938,  0.02383236],
       [ 0.01416349, -0.06268777],
       [ 0.01416349, -0.10594783],
       [ 0.05627116, -0.07710779],
       [ 0.18259418,  0.12477251],
       [ 0.21066596,  0.21129264],
       [ 0.08434294, -0.03384772],
       [-0.01390829, -0.07710779],
       [-0.02794418, -0.12036785],
       [-0.07005185, -0.09152781],
       [ 0.0001276 ,  0.00941234],
       [-0.05601596, -0.0194277 ],
       [-0.04198007, -0.00500768],
       [ 0.09837883,  0.06709243],
       [ 0.11241472,  0.09881648],
       [ 0.1404865 ,  0.1132365 ],
       [ 0.02819938,

In [38]:
# OLS оценка коэффициентов центрированной регрессии
w_hat_st=np.linalg.inv(A_st.T@A_st)@A_st.T@y_st.values
w_hat_st

array([[0.19044768],
       [0.62001517]])