In [1]:
import numpy as np
import pandas as pd

In [ ]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

In [ ]:
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

In [ ]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1] / apartment[0]

In [ ]:
apartment = np.delete(apartment, [0, 1])

In [ ]:
apartment = np.append(apartment, share_living_space)
display(apartment)

In [ ]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [2]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [7]:
Hut_Paradise = Hut_Paradise_DF.values

In [8]:
Hut_Paradise[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [9]:
Hut_Paradise[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [10]:
Hut_Paradise[2, 3]

10

In [11]:
len(Hut_Paradise)

9

In [12]:
Hut_Paradise[:, 1] - Hut_Paradise[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [13]:
Hut_Paradise[:, 0] * 0.4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [14]:
time_demo = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [19]:
(Hut_Paradise[:, 4] * time_demo).sum()

1348

In [20]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [21]:
print('(u, v)', u@v)
print('(v, w)', v@w)
print('(u, w)', u@w)

(u, v) 0
(v, w) 0
(u, w) 0


In [23]:
s = v*2 + (-3)*w

In [24]:
s@u

0

In [28]:
(u / np.linalg.norm(u)).round(3)

array([0.866, 0.   , 0.289, 0.289, 0.289])

In [29]:
(v / np.linalg.norm(v)).round(3)

array([ 0.   ,  0.333,  0.   ,  0.667, -0.667])

In [30]:
(w / np.linalg.norm(w)).round(3)

array([ 0.213, -0.853, -0.213,  0.   , -0.426])

In [41]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [42]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [43]:
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [44]:
Inc * (1 - 0.13)

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [48]:
P = Inc * (1 - 0.13) - Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [49]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [50]:
A@x

array([26, 30])

In [51]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [53]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [54]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [55]:
g = np.array([x,y,z]).T

In [56]:
g.T@g

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [57]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [60]:
Count = Count_DF.values
Count

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]], dtype=int64)

In [61]:
Price = Price_DF.values
Price

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [64]:
Count[1] * Price[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [65]:
com = np.array([0.2,0.2,0.3,0.1,0.1])

In [70]:
(com @ (Count * Price).T).T

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [73]:
p = np.array([0.8,0.8,0.7,0.9,0.9])

In [74]:
(p @ (Count * Price).T).T

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])